version: '3.7'

services:
  recipe-app-frontend:
    build: .
    image: recipe-app-frontend:latest
    container_name: recipe-app-frontend
    environment:
      - GRPC_PROXY=8082
      - GRPC_LOCATION=0.0.0.0
    restart: always
networks:
  default:
    external:
      name: recipe
