version: '3.7'

services:
  recipe-app-frontend:
    build: .
    image: recipe-app-frontend:latest
    container_name: recipe-app-frontend
    ports:
      - 80:80
    environment:
      - SERVER_ADDRESS=recipe-app-backend
      - SERVER_PORT=3001
    restart: always
networks:
  default:
    name: recipe
