export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_RESPONSE = 'ADD_RECIPE_RESPONSE';
export const GET_RECIPE_REQUEST = 'GET_RECIPE_REQUEST';
export const GET_RECIPE_RESPONSE = 'GET_RECIPE_RESPONSE';
export const GET_ALL_RECIPES_REQUEST = 'GET_ALL_RECIPES_REQUEST';
export const GET_ALL_RECIPES_RESPONSE = 'GET_ALL_RECIPES_RESPONSE';
export const UPDATE_RECIPE_REQUEST = 'UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_RESPONSE = 'UPDATE_RECIPE_RESPONSE';
export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_RESPONSE = 'DELETE_RECIPE_RESPONSE';

export const PING = 'PING';
export const PONG = 'PONG';
