// Add
export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_RESPONSE = 'ADD_RECIPE_RESPONSE';
// Edit
export const EDIT_RECIPE_REQUEST = 'EDIT_RECIPE_REQUEST';
export const EDIT_RECIPE_RESPONSE = 'EDIT_RECIPE_RESPONSE';
// Delete
export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_RESPONSE = 'DELETE_RECIPE_RESPONSE';
// Get
export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST';
export const GET_RECIPES_RESPONSE = 'GET_RECIPES_RESPONSE';
export const GET_RECIPE_BY_ID_REQUEST = 'GET_RECIPE_BY_ID_REQUEST';
export const GET_RECIPE_BY_ID_RESPONSE = 'GET_RECIPE_BY_ID_RESPONSE';
// Error
export const ERROR = 'ERROR';
// Ping
export const PING = 'PING';
export const PONG = 'PONG';
